language: scala
jdk:
- oraclejdk8

scala:
- 2.11.11
- 2.12.8

script:
- curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.4/0.3.4 && chmod +x ~/bin/mill
- mill hamster[$TRAVIS_SCALA_VERSION].jvm.test
- mill hamster[$TRAVIS_SCALA_VERSION].js.compile

jobs:
  include:
    - stage: release
      if: |
        repo = 'scala-hamsters/hamsters' AND \
        tag IS present
      script:
      - mill hamster.__.publish --gpgPassphrase "${GPG_PASSPHRASE}" --release true --sonatypeCreds "${SONATYPE_CREDENTIALS}"